# Generated by Django 4.0.2 on 2022-03-09 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_genre_primary_genre_alter_genre_sub_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(default='Jazz', on_delete=django.db.models.deletion.CASCADE, to='musicapp.genre'),
        ),
    ]
