# Generated by Django 4.0.2 on 2022-03-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_artist_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='album',
            field=models.CharField(default='', max_length=255),
        ),
    ]
