# Generated by Django 4.0.2 on 2022-04-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_remove_artist_genre_remove_artist_year_delete_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='album',
        ),
    ]
