# Generated by Django 4.0.2 on 2022-04-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_remove_artist_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='song',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
