# Generated by Django 4.0.2 on 2022-03-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Ratings',
        ),
    ]
